"""
Interactive py3Dmol molecule viewer with widget controls.
"""

import numpy as np
import ipywidgets as widgets
from IPython.display import display, clear_output

try:
    import py3Dmol
    PY3DMOL_AVAILABLE = True
except ImportError:
    PY3DMOL_AVAILABLE = False


class InteractivePy3DmolViewer:
    """Interactive 3D molecule viewer using py3Dmol with ipywidgets controls."""
    
    # Style presets
    STYLES = {
        'Ball & Stick': {'stick': {'radius': 0.15}, 'sphere': {'scale': 0.3}},
        'Sphere (CPK)': {'sphere': {'scale': 0.5}},
        'Stick Only': {'stick': {'radius': 0.2}},
        'Line': {'line': {}},
        'Cartoon': {'cartoon': {'color': 'spectrum'}},
        'Surface': {'surface': {'opacity': 0.8}}
    }
    
    # Background color presets
    BG_COLORS = ['white', 'black', 'lightgray', '#e6f3ff', '#1a1a2e', '#0f0f23']
    
    def __init__(self, molecules=None):
        """
        Initialize the interactive py3Dmol viewer.
        
        Parameters:
        -----------
        molecules : list, optional
            List of DrugMolecule objects to visualize
        """
        if not PY3DMOL_AVAILABLE:
            raise ImportError("py3Dmol is required. Install with: pip install py3Dmol")
        
        self.molecules = molecules or []
        self.current_molecule = None
        
        # Create widgets
        self._create_widgets()
        
        # Output widget for viewer
        self.viewer_output = widgets.Output()
        self.info_output = widgets.Output()
    
    def _create_widgets(self):
        """Create all control widgets."""
        # Molecule selector
        self.molecule_dropdown = widgets.Dropdown(
            options=[],
            description='Molecule:',
            style={'description_width': 'initial'},
            layout=widgets.Layout(width='300px')
        )
        
        # Style selector
        self.style_dropdown = widgets.Dropdown(
            options=list(self.STYLES.keys()),
            value='Ball & Stick',
            description='Style:',
            style={'description_width': 'initial'},
            layout=widgets.Layout(width='200px')
        )
        
        # Background color
        self.bg_dropdown = widgets.Dropdown(
            options=self.BG_COLORS,
            value='white',
            description='Background:',
            style={'description_width': 'initial'},
            layout=widgets.Layout(width='200px')
        )
        
        # Viewer dimensions
        self.width_slider = widgets.IntSlider(
            value=500,
            min=300, max=900, step=50,
            description='Width:',
            style={'description_width': 'initial'},
            layout=widgets.Layout(width='250px')
        )
        
        self.height_slider = widgets.IntSlider(
            value=400,
            min=250, max=700, step=50,
            description='Height:',
            style={'description_width': 'initial'},
            layout=widgets.Layout(width='250px')
        )
        
        # Display options
        self.show_properties = widgets.Checkbox(
            value=True,
            description='Show properties',
            style={'description_width': 'initial'}
        )
        
        self.spin = widgets.Checkbox(
            value=False,
            description='Auto-rotate',
            style={'description_width': 'initial'}
        )
        
        # Buttons
        self.refresh_button = widgets.Button(
            description='🔄 Refresh',
            button_style='info',
            layout=widgets.Layout(width='100px')
        )
        self.refresh_button.on_click(self._on_refresh)
    
    def load_molecules(self, molecules):
        """
        Load molecules into the viewer.
        
        Parameters:
        -----------
        molecules : list
            List of DrugMolecule objects
        """
        self.molecules = molecules
        
        # Update dropdown options
        molecule_names = [mol.name for mol in molecules]
        self.molecule_dropdown.options = molecule_names
        
        if molecule_names:
            self.molecule_dropdown.value = molecule_names[0]
            self.current_molecule = molecules[0]
    
    def _get_xyz_string(self, mol):
        """
        Generate XYZ string from DrugMolecule.
        
        Uses mol.elements and mol.initial_coords which are 
        auto-generated by DrugMolecule._parse_xyz()
        """
        if mol.initial_coords is None or len(mol.elements) == 0:
            return None
        
        xyz = f"{len(mol.elements)}\n{mol.name}\n"
        for element, coord in zip(mol.elements, mol.initial_coords):
            xyz += f"{element} {coord[0]:.4f} {coord[1]:.4f} {coord[2]:.4f}\n"
        
        return xyz
    
    def _update_viewer(self):
        """Update the 3D viewer with current settings."""
        # Get current molecule
        molecule_name = self.molecule_dropdown.value
        mol = next((m for m in self.molecules if m.name == molecule_name), None)
        
        if mol is None:
            with self.viewer_output:
                clear_output(wait=True)
                print(f"❌ Molecule '{molecule_name}' not found")
            return
        
        self.current_molecule = mol
        
        # Get XYZ data
        xyz_data = self._get_xyz_string(mol)
        if xyz_data is None:
            with self.viewer_output:
                clear_output(wait=True)
                print(f"❌ No 3D coordinates available for '{molecule_name}'")
            return
        
        # Create viewer
        with self.viewer_output:
            clear_output(wait=True)
            
            width = self.width_slider.value
            height = self.height_slider.value
            
            viewer = py3Dmol.view(width=width, height=height)
            viewer.addModel(xyz_data, "xyz")
            
            # Apply style
            style_name = self.style_dropdown.value
            style_dict = self.STYLES.get(style_name, self.STYLES['Ball & Stick'])
            viewer.setStyle(style_dict)
            
            # Set background
            viewer.setBackgroundColor(self.bg_dropdown.value)
            
            # Zoom to fit
            viewer.zoomTo()
            
            # Auto-rotate if enabled
            if self.spin.value:
                viewer.spin(True)
            
            viewer.show()
        
        # Show properties if enabled
        if self.show_properties.value:
            self._show_properties(mol)
        else:
            with self.info_output:
                clear_output(wait=True)
    
    def _show_properties(self, mol):
        """Display molecular properties."""
        with self.info_output:
            clear_output(wait=True)
            
            # Ensure descriptors are calculated
            if not mol.properties:
                mol.calculate_descriptors()
            
            props = mol.properties
            
            print(f"📊 {mol.name}")
            print("─" * 40)
            print(f"   MW: {props.get('MW', 0):.1f} Da    LogP: {props.get('LogP', 0):.2f}")
            print(f"   TPSA: {props.get('TPSA', 0):.1f} Ų    QED: {props.get('QED', 0):.3f}")
            print(f"   HBD: {props.get('HBD', 0)}    HBA: {props.get('HBA', 0)}    RotBonds: {props.get('RotatableBonds', 0)}")
            
            # Drug-likeness check
            lipinski_ok = (
                props.get('MW', 0) <= 500 and
                props.get('LogP', 0) <= 5 and
                props.get('HBD', 0) <= 5 and
                props.get('HBA', 0) <= 10
            )
            status = "✅ Drug-like" if lipinski_ok else "⚠️ Lipinski violations"
            print(f"   {status}")
    
    def _on_refresh(self, button):
        """Handle refresh button click."""
        self._update_viewer()
    
    def _setup_callbacks(self):
        """Setup widget callbacks for auto-update."""
        # Update on any widget change
        self.molecule_dropdown.observe(lambda c: self._update_viewer(), names='value')
        self.style_dropdown.observe(lambda c: self._update_viewer(), names='value')
        self.bg_dropdown.observe(lambda c: self._update_viewer(), names='value')
        self.width_slider.observe(lambda c: self._update_viewer(), names='value')
        self.height_slider.observe(lambda c: self._update_viewer(), names='value')
        self.show_properties.observe(lambda c: self._update_viewer(), names='value')
        self.spin.observe(lambda c: self._update_viewer(), names='value')
    
    def display(self):
        """
        Create and return the complete viewer interface.
        
        Returns:
        --------
        ipywidgets.VBox
            The complete viewer interface widget
        """
        # Setup callbacks
        self._setup_callbacks()
        
        # Row 1: Molecule selector and style
        row1 = widgets.HBox([
            self.molecule_dropdown,
            self.style_dropdown,
            self.bg_dropdown
        ])
        
        # Row 2: Dimensions
        row2 = widgets.HBox([
            self.width_slider,
            self.height_slider
        ])
        
        # Row 3: Options and refresh
        row3 = widgets.HBox([
            self.show_properties,
            self.spin,
            self.refresh_button
        ])
        
        # Viewer area
        viewer_area = widgets.VBox([
            self.viewer_output,
            self.info_output
        ])
        
        # Complete interface
        interface = widgets.VBox([
            widgets.HTML("<h4>🔮 Interactive 3D Molecule Viewer (py3Dmol)</h4>"),
            row1,
            row2,
            row3,
            viewer_area
        ])
        
        # Initial display
        if self.molecules:
            self._update_viewer()
        
        return interface
    
    def show_molecule(self, molecule_name):
        """
        Display a specific molecule by name.
        
        Parameters:
        -----------
        molecule_name : str
            Name of the molecule to display
        """
        if molecule_name in self.molecule_dropdown.options:
            self.molecule_dropdown.value = molecule_name
            self._update_viewer()
        else:
            print(f"❌ Molecule '{molecule_name}' not found in loaded molecules")
    
    def set_style(self, style_name):
        """
        Set the visualization style.
        
        Parameters:
        -----------
        style_name : str
            One of: 'Ball & Stick', 'Sphere (CPK)', 'Stick Only', 'Line', 'Cartoon', 'Surface'
        """
        if style_name in self.STYLES:
            self.style_dropdown.value = style_name
            self._update_viewer()
        else:
            print(f"❌ Unknown style '{style_name}'. Available: {list(self.STYLES.keys())}")
